# ======= 
#  
# Project Details 
#
# =======   
project-name: "hello-world" # For WordPress projects, this must be identical to theme name
GA-code: null  #eg -"UA-66481277-1"
# ======= 
#  
# BrowserSync for live-reloading  
#
# =======   
browserSync: 
  server: 
    baseDir: "public"    
# ======= 
#  
# Javascript is compiled via JSPM    
#
# =======
js: 
  src: "js"
  dest: "js"
  extractSharedJs: true
  entries: 
    app: 
      - "./app.js"
    page: 
      - "./page.js"
  extensions: 
    - "js"
# =======   
#
# SASS/SCSS for stylesheets   
#
# =======    
sass: 
  src: "./src/scss/*.scss"
  dest: "./public/css"
  watch: "./src/scss/*.scss"
  autoprefix_browsers: ['last 2 version', 'ie 9']
  settings: 
    indentedSyntax: false # Set to true if you want to use sass indented syntax
    errLogToConsole: errLogToConsole
# =======   
#
# Jade/Twig for template engines   
#
# =======       
templates: 
  engine: 'twig' #enter 'twig', 'jade', or false.  False means you're just writing HTML
                #if you enter false the remaining settings will be ignored as the task will return
  twig:
    src: "./src/twig/*.twig"  
    dest: "./src/html"
    watch: "./src/twig/*.twig"
    data: "./src/twig/data"
  jade:
    src: "./src/jade/*.jade"  
    dest: "./src/html"
    watch: "./src/jade/*.jade"
    data: "./src/jade/data"

# =======   
#
# Optimize PNG, JPEG, GIF and SVG for web   
#
# =======  
images: 
  src: "./src/img/**"
  dest: "./public/img"
# =======   
#
# Generate Favicons for any modern web app 
#
# =======  
favicon:
  src: "test"    
# =======   
#
# Prep fonts for @font-face   
#
# =======  
fonts: 
  src: "fonts"
  dest: "fonts"
  extensions: 
    - "woff2"
    - "woff"
    - "eot"
    - "ttf"
    - "svg"
# =======   
#
# Generate Icon Font from SVGs
#
# =======  
iconFont: 
  src: "icons"
  dest: "fonts"
  sassDest: "generated"
  extensions: 
    - "woff2"
    - "woff"
    - "eot"
    - "ttf"
    - "svg"
# =======   
#
# Create a sprite for speedy web use
#
# =======  
svgSprite: 
  src: "sprites"
  dest: "img"
  extensions: 
    - "svg"
