<?php
// remove RSD (really simple discver) meta link for pingbacks
remove_action('wp_head', 'rsd_link');
// remove generated by wordpress meta tag
remove_action( 'wp_head', 'wp_generator' );
// disable emoji code
remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
remove_action( 'wp_print_styles', 'print_emoji_styles' );
